# 数据集
CAR = "car"
CIFAR10 = "cifar-10-batches-py"
CIFAR100 = "cifar-100-python"
MNIST = "MNIST"
SVHN = "SVHN"
WINE = "wine"

DATASETS = [CIFAR10, CIFAR100, MNIST, SVHN, WINE, CAR]
CNNDATASETS = DATASETS[:4]
MLPDATASETS = DATASETS[4:]

BATCHSIZE = 500
